In [1]:
import numpy as np
a = np.random.rand(3,4)
b = np.argmax(a, axis=0)

In [3]:
print(a)
print(b)

[[0.37186436 0.94514891 0.11212519 0.62368763]
 [0.02430414 0.92985997 0.78472659 0.332152  ]
 [0.17936938 0.65082475 0.89679173 0.1480437 ]]
[0 0 2 0]


In [6]:
labels = np.random.randint(0, 10, (3,))
print(labels)
print(labels[b])

[2 0 8]
[2 2 8 2]


In [7]:
print('a={0:.3f}'.format(0.3))

a=0.300


In [ ]:
np.sum(a)